# Generated by Django 3.0.8 on 2020-07-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='uemail',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='uname',
            field=models.CharField(max_length=100),
        ),
    ]
