# Generated by Django 3.0.8 on 2020-08-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_customer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
    ]
