# Generated by Django 3.0.8 on 2020-09-20 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_remove_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='udate',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='utime',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
