# Generated by Django 3.0.8 on 2020-09-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_auto_20200920_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='udate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='utime',
        ),
    ]
