# Generated by Django 3.0.8 on 2020-09-20 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_auto_20200920_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='udate',
            field=models.DateField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
