# Generated by Django 3.0.8 on 2020-09-20 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0010_customer_udate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='utime',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
