# Generated by Django 3.0.8 on 2020-09-21 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0012_remove_customer_utime'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='utime',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='udate',
            field=models.CharField(max_length=100),
        ),
    ]
