# Generated by Django 3.0.8 on 2020-09-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0013_auto_20200921_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambulance_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_no', models.CharField(max_length=100)),
                ('ambulance_type', models.CharField(max_length=100)),
            ],
        ),
    ]
