# Generated by Django 3.0.8 on 2020-09-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0014_ambulance_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance_details',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
